### ISSUE TITLE
Add testcases for API endpoints

### ISSUE THREAD

**Issue by JesseLacroix** [SENG499-COMPANY4/Algorithm-1#54]
Add tests for:
Schedule generation:
GET 

- [x] - Valid case
- [x] - No token case

POST

- [x] - Valid case
- [x] - Invalid case
- [x] - No token case

Validation
POST

- [x] - Valid case
- [x] - Invalid case
- [x] - No token case

Lock courses
PUT

- [x] - Valid case
- [x] - Invalid case
- [x] - No token case
- [ ] 

API responses:
200 range: Good response
400 range: Bad response from the request
500 range: Bad response from an error in the code

**Comment by DeweiYu** [comment]
I wrote the preliminary test case for get without the token, the post will valid case, invalid case, and without token
